-- Add Yahoo Finance as a persisted market-data provider.
ALTER TABLE `Instrument` MODIFY `provider` ENUM('TWELVEDATA', 'FINNHUB', 'POLYGON', 'ALPHAVANTAGE', 'YAHOOFINANCE', 'OTHER') NOT NULL;
ALTER TABLE `QuoteCache` MODIFY `provider` ENUM('TWELVEDATA', 'FINNHUB', 'POLYGON', 'ALPHAVANTAGE', 'YAHOOFINANCE', 'OTHER') NOT NULL;
