-- AlterEnum
ALTER TABLE `Instrument`
    MODIFY `provider` ENUM('TWELVEDATA', 'FINNHUB', 'POLYGON', 'ALPHAVANTAGE', 'YAHOOFINANCE', 'OTHER') NOT NULL;

-- AlterEnum
ALTER TABLE `QuoteCache`
    MODIFY `provider` ENUM('TWELVEDATA', 'FINNHUB', 'POLYGON', 'ALPHAVANTAGE', 'YAHOOFINANCE', 'OTHER') NOT NULL;
